function  [ out ] = get_materialHysteresis( matDef, inputData, numIncr, localOpenSeesPath )
%% DESCRIPTION

% INPUT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% matDef              : material definition string from OpenSees
% inputData           : a vector of input deformation/strain time history
% numIncr             : num of points to include between inputData(i) and inputData(i+1)
% localOpenSeesPath   : full path to OpenSees executable

% OUTPUT
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% out                 : [deformation force] or [strain stress]

%% Function
[matDef, localOpenSeesPath] = convertStringsToChars(matDef, localOpenSeesPath);
inputData = arrayfun(@(x) num2str(x), inputData, 'UniformOutput', 0);
temp = strsplit(matDef);
matTag = temp{3};

materialTesterFid = fopen('matTest.tcl','w+');
fprintf(materialTesterFid,['wipe;\n']);
fprintf(materialTesterFid,['model testUniaxial;\n']);
fprintf(materialTesterFid,['set matTag ', num2str(matTag,'%u'), ';\n']);
fprintf(materialTesterFid,['set strainHistory {', strjoin(inputData), '};\n']);
fprintf(materialTesterFid,['set fileOut "hysteresis_matTag_$matTag.txt";\n']);
fprintf(materialTesterFid,['set out [open $fileOut w];\n']);
fprintf(materialTesterFid,[matDef '\n']);
fprintf(materialTesterFid,...
    ['uniaxialTest $matTag;\n',...
    'set strain 0.0;\n',...
    'set count 1;\n',...
    'set iTime 0;\n',...
    'set strain [expr $strain];\n',...
    'strainUniaxialTest $strain;\n',...
    'set stress [stressUniaxialTest];\n',...
    'set tangent [tangUniaxialTest];\n',...
    'set iTime [expr $iTime+1];\n',...
    'puts $out "$strain $stress";\n',...
    'foreach {strainExtremeVal} $strainHistory {\n',...
    '		set numIncr ' num2str(numIncr,'%u') ';\n',...
    '		set strainIncr [expr ($strainExtremeVal - $strain)/$numIncr];\n',...
    '		for {set i 0} {$i < $numIncr} {incr i 1} {\n',...
    '			set strain [expr $strain+$strainIncr];\n',...
    '			strainUniaxialTest $strain;\n',...
    '			set stress [stressUniaxialTest];\n',...
    '			set tangent [tangUniaxialTest];\n',...
    '			set iTime [expr $iTime+1];\n',...
    '			puts $out "$strain $stress";\n',...
    '		}\n',...
    '}\n',...
    'close $out;\n',...
    'puts "MATERIAL TESTER RAN SUCCESSFULLY!";\n',...
    'wipe;\n'...
    ]);
fclose(materialTesterFid);

[~, ~] = system(['"',localOpenSeesPath,'" "matTest.tcl"']);

fid = fopen(['hysteresis_matTag_' num2str(matTag,'%u') '.txt'],'r');
dataRead = textscan(fid, repmat('%f ',1,2), 'CollectOutput',true);
out = dataRead{1};
fclose(fid);
delete(['hysteresis_matTag_' num2str(matTag,'%u') '.txt']);
delete('matTest.tcl');

end